### ISSUE TITLE
Create Palette overview

### ISSUE THREAD

**Issue by pietryszak** [sainnhe/gruvbox-material#149]
Gruvbox has a super useful graphic with all colors used in it. It's nice when you just need colors to create you own config for apps. 
Gruvbox-material instead that hide colors in issues  or in the code.

It's good to create something like that, for quick look at official color palete:
![image](https://user-images.githubusercontent.com/45850093/197764871-1a1750a5-e651-48aa-9003-030b64f72483.png)

**Comment by antoineco** [comment]
I started creating something similar for the Everforest color scheme (one of @sainnhe's other themes for Vim): ~https://github.com/antoineco/sainnhe-everforest/blob/palette/palette.md~

Would a similar format be useful here?

**Comment by pietryszak** [comment]
![image](https://user-images.githubusercontent.com/45850093/197777289-1c29960e-968a-4c4c-b258-33576bc16035.png)
The faster way is add a color on image too, instead only in table. But good idea.

**Comment by antoineco** [comment]
If you know something that can automate that work I'm all ears.

**Comment by pietryszak** [comment]
I think in gruvbox they just add in image, like create image in gimp. I have no idea that automatic solution exsist

**Comment by antoineco** [comment]
FYI, we added a [Color Palette and Highlighting Semantics](https://github.com/sainnhe/everforest/blob/master/palette.md) doc to the sainnhe/everforest color scheme.

A lot of concepts are shared between the two themes, so I have plans to port something similar here in the near future.

**Comment by Aonodensetsu** [comment]
can you star issues? because this should absolutely be a priority, this is the third time i'm scouring this theme's files for color hex values, [which are here btw](https://github.com/sainnhe/gruvbox-material/blob/master/autoload/gruvbox_material.vim#L36)

the easiest way i found to get all the colors in a quick way is to download [this](https://plugins.jetbrains.com/plugin/19469-gruvbox-material) and open it up with 7zip to get the theme json

**Comment by antoineco** [comment]
@Aonodensetsu you can add a thumb up to the original message.

How is downloading a zip and opening a JSON file quicker than looking at the value inside the Vim file you shared?

**Comment by Aonodensetsu** [comment]
The vim file has colors split into three palettes, with variants for each of light/dark hard/medium/soft, with names not reflecting what they are since vim uses highlight groups, the json file instead, has a single (dark/medium) palette, with hex values assigned to color names (darkRed, green, fg) which can be easily repurposed for other uses

i also could not find all the colors in vim regardless since some are simply not used, but they should be included in the palette regardless since another use might depend on them (darkAqua (bg_aqua) is missing for example)

regardless, both those methods are hacks and the palette should have a list of colors in the README, either as text, table or png

i don't have the full canonical list of colors but i probably could spin something up tomorrow as a draft

**Comment by Aonodensetsu** [comment]
did as i said i would, written in python for around 0 hassle in making them, need to make it a bit more fancy - [preview generator](https://github.com/Aonodensetsu/palette-preview-generator)

**Comment by Aonodensetsu** [comment]
version 5 released - generally looks really nice and is dead-simple to use, this is the "usable" phase and the next version in a few weeks will be a full rewrite to fix any kinks that might have been missed

**Comment by Aonodensetsu** [comment]
Made a quick regex search through the vim file to autogenerate the correct python table for each combination of colors.
Here is the regex: `.*\\\s'(.+?)':\s+\['(.+?)'.*\r\n`, attached is a zip containing generated PNGs. Since I don't have the colors used by the author himself, there is only what could be extracted from code, so some colors are missing and in general colors have pretty bad names (highlight groups instead of a color name), but that is not a big problem. The only thing to do now is to wait for the authors to make a canonical version.
[gruvbox-material.zip](https://github.com/sainnhe/gruvbox-material/files/10472852/gruvbox-material.zip)

**Comment by Visual-Dawg** [comment]
To allow for easy copying of the values, you could create an `svg` with the text and colors. 
For that the property [`foreignObject`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject) is used and it works for Github.
