### ISSUE TITLE
[Feature Request] More colors

### ISSUE THREAD

**Issue by EricDriussi** [sainnhe/gruvbox-material#156]
Hi there!
Loving the theme, thanks for putting in the work.

So I'm not quite sure how to express this, I'll do my best:
For any given code snippet, there seems to be a bit of color repetition for seemingly different elements.

So for example, with `catppuccin`:
![image](https://user-images.githubusercontent.com/46979145/202849497-55b38359-f48e-4c21-9e24-a758bf0d7f42.png)

While `gruvbox-material`:
![image](https://user-images.githubusercontent.com/46979145/202849630-82b76f1a-9695-4146-a465-e00a9c6ce298.png)

(Notice for example lines 7, 15, 16 and 21)

Mind you this is with the same config, except for `gruvbox-material` specifics that don't seem to affect the output, like

``` 
set termguicolors
set background=dark
let g:gruvbox_material_background = 'hard'
let g:gruvbox_material_foreground = 'mix'
let g:gruvbox_material_better_performance = 1
let g:gruvbox_material_enable_italic = 1
let g:gruvbox_material_visual = 'background'
```

I'm not sure if this is the expected behavior but it just feels like something is missing.

I understand that versions and configs are not really relevant for this issue, although if mistaken I can attach whatever information might be needed.

**Comment by antoineco** [comment]
@EricDriussi could you please elaborate what repetition you're referring to? What elements exactly?

---

I think I can tell with a high certainty that Gruvbox Material is not going to get _more colors_, simply because a color sheme is created with a certain palette and those colors are assigned to very specific highlight semantics. Both make the color scheme's identity.

E.g. a color scheme based on 3 colors will distribute highlights differently from a color sheme with 30 colors. Is the theme with 30 colors better than the one with 3? Depends who you ask.

**Comment by sainnhe** [comment]
Variables are expected to be White, I've added some new tokens in https://github.com/sainnhe/gruvbox-material/commit/421ccc28df2b5c8aef06b40160d539684fd1e771 , could you get it a try?

**Comment by EricDriussi** [comment]
@sainnhe That's exactly what I was referring to, looks awesome!
Thanks a lot!!
