### ISSUE TITLE
Add suppor for nvim-navic

### ISSUE THREAD

**Issue by xeluxee** [sainnhe/gruvbox-material#166]
https://github.com/SmiteshP/nvim-navic is a Neovim plugin to show current code context in winbar or statusline.
Its highlight groups are similar to `CmpItemKind*` ones, e.g. `NavicIconsMethod` and `NavicIconsConstant`. They can be found in its README.

**Comment by sainnhe** [comment]
Sorry but I'm too busy recently, I'll look into it when I have time.

And your can also add support for it by yourself, PR is always welcome :)

**Comment by antoineco** [comment]
I use navic too[^1]:

![image](https://user-images.githubusercontent.com/3299086/222371136-a2694eb5-5d14-43d1-bfaa-7fcfb6dc01bc.png)

I agree with the suggestion, adding colors would be a nice touch. It's also not a big risk (i.e. won't disturb users) because navic's highlights are [off by default](https://github.com/SmiteshP/nvim-navic/blob/7e9d2b2b601149fecdccd11b516acb721e571fe6/lua/nvim-navic/init.lua#L363).

You can experiment with different settings in your own Neovim config by declaring an `augroup` like below, then submit a proposal once you're happy with the result:

```lua
-- Apply custom highlights on colorscheme change.
-- Must be declared before executing ':colorscheme'.
grpid = vim.api.nvim_create_augroup('custom_highlights_gruvboxmaterial', {})
vim.api.nvim_create_autocmd('ColorScheme', {
  group = grpid,
  pattern = 'gruvbox-material',
  command = -- navic icon colors
            'hi NavicIconsMethod   guifg=#c35e0a |' ..
            'hi NavicIconsConstant guifg=#b47109'
})
```

Ideally we should align on the colors used in LSP autocompletions:

![image](https://user-images.githubusercontent.com/3299086/222375435-1a268677-1c79-4e94-baae-1ebc91a6c72f.png)

[^1]: Here shown with Everforest, a sister colorscheme from sainnhe originally adapted from gruvbox-material.

**Comment by xeluxee** [comment]
Since [nvim-cmp](https://github.com/hrsh7th/nvim-cmp), [nvim-navic](https://github.com/SmiteshP/nvim-navic) and [aerial.nvim](https://github.com/stevearc/aerial.nvim) require highlights for LSP item kinds, we could define a color for each kind and assign (or link) highlight groups accordingly, as [onedark.nvim](https://github.com/navarasu/onedark.nvim/blob/master/lua/onedark/highlights.lua#L709-L713) does
