### ISSUE TITLE
Wrong colors for tag and tag.attribute for nvim-treesitter-tsx?

### ISSUE THREAD

**Issue by tomasjm** [sainnhe/gruvbox-material#177]
Hello,
I don't know if a problem of the theme, the parser or my configuration. I think the color is wrong from what can be seen in the image for "tag" and "tag.attribute" when using Tree-sitter "tsx" parser (nvim-treesitter-tsx) using nvim 0.9.0. ```:TSInstall tsx ```

![screenshot](https://user-images.githubusercontent.com/37565345/233906956-ff888a9a-0a16-48f6-9469-bf85b43e9324.jpg)

![image](https://user-images.githubusercontent.com/37565345/233907614-11c4d76d-2b16-46fe-850c-818dfa1ed6ab.png)
![image](https://user-images.githubusercontent.com/37565345/233907580-e01bf4d2-e409-4d6f-b807-de2eea90bf67.png)

I was trying to add colors by linking but I failed. I think that apparently other highlight groups are overriding the colors?
Due to my limitation of treesitter knowledge I can't do more.

I want to learn to fix it with some help, if this is a problem of the theme, so I can add support for tsx if is necessary

**Comment by antoineco** [comment]
Nice catch.

I know nothing about tsx, but it looks like those tags are being [categorized as Constructor](https://github.com/nvim-treesitter/nvim-treesitter/blob/v0.9.0/queries/jsx/highlights.scm#L18-L34), and Tag with a lesser priority.

Could you please try adding this autocmd to your Neovim config, and see whether the look and feel improves?

```lua
-- Apply custom highlights on colorscheme change.
-- Must be declared before executing ':colorscheme'.
local grpid = vim.api.nvim_create_augroup('custom_highlights_gruvboxmaterial', {})
vim.api.nvim_create_autocmd('ColorScheme', {
  group = grpid,
  pattern = 'gruvbox-material',
  callback = function()
    local function hl_lnk(src, trgt)
      vim.api.nvim_set_hl(0, src, { link = trgt })
    end

    hl_lnk('@constructor.tsx', '@type')
    hl_lnk('@tag.attribute.tsx', '@property')
  end
})
```

![image](https://user-images.githubusercontent.com/3299086/233924594-7d439c12-826b-4727-be89-d73b7f23fa6a.png)

**Comment by antoineco** [comment]
One drawback of implementing this change in the colorscheme is that actual constructors are now highlighted like `@type`.

![image](https://user-images.githubusercontent.com/3299086/233937222-5ae3bd0a-1db1-4a97-ad85-26babd9b1503.png)

Luckily there aren't that many tokens identified as `@constructor` in JS/TS (I think). However, I'm a bit reluctant to make this the default, because we would be changing the semantics globally just to get around the current behaviour of Neovim's `tsx` queries. It would be great if these queries could highlight React types in markup tags as `@tag.constructor`—or anything else under `@tag` really—so that colorschemes can apply meaningful highlights in markup blocks.

Maybe something worth suggesting upstream. The parser is already identifying everything correctly, so it would be only a matter of tuning the queries to separate React tags (constructors) and attributes from their JavaScript/TypeScript counterpart.

![image](https://user-images.githubusercontent.com/3299086/233945648-03c36e10-ee54-4c64-a0b6-8f5c16c66b2f.png)
![image](https://user-images.githubusercontent.com/3299086/233945828-5e839668-2521-4077-bbc5-573ec0154d51.png)

**Comment by tomasjm** [comment]
Hey, thank you, now I understand a little more the problem and learn how to set colors in a good way.

I was testing with some other colorschemes like catppuccin and it seems that they are coloring tsx files differently than ts files. Actually is strange to put class definitions in .tsx files if not React with Class Components imo, so I think that the constructor sharing the color is not that bad, also thinking that tsx files will have more jsx as are used principally for React projects and .ts will probably have more classes.

Others themes are also separating tag and constructor color attributes for html tags and react components.

Tried with some colors to copy, as an example, catppuccin behaviour only for .tsx files with function and class component:
```
highlight! link @tag.tsx Red
highlight! link @constructor.tsx Orange 
highlight! link @tag.attribute.tsx Blue 
```

![image](https://user-images.githubusercontent.com/37565345/233956610-20f0c48a-e289-40d7-83b6-2e3b2ff447a6.png)
![image](https://user-images.githubusercontent.com/37565345/233956715-74d5dae0-f00e-423a-ba6d-973553bfc5a1.png)

Probably exists a better match of colors to follow the theme guidelines, but I like a lot the readability of the example 

EDIT: Another example using only html tags (red) and another using jsx components (orange):
<img width="894" alt="ex1" src="https://user-images.githubusercontent.com/37565345/233960188-8c1aab3d-5a77-473a-bf01-a39931619454.png">
<img width="682" alt="ex2" src="https://user-images.githubusercontent.com/37565345/233960202-4b9e4559-91e7-4595-b0f1-4e910fca6d20.png">

**Comment by antoineco** [comment]
OK thanks for your feedback 👍

It's unfortunate that two tokens of the same color ended up next to each other in React. I see that catppuccin also added the exact same overrides for `tsx` files, so they probably ran into the same issue.

I trust your jugement regarding the rare usage of constructors in `tsx` files and will implement the change in the colorscheme whenever I find the time to do it. As colorscheme authors we have to remain faithful to the [themes' semantics](https://github.com/sainnhe/everforest/blob/master/palette.md#highlights)[^1] and provide consistent defaults.

- I'm going to link `@constructor.tsx` to `@type` because these _do_ refer to types. Doing this addresses the problem of "constructor" (types) being the same color as their neighboring attributes and delimiters.

- Tag attributes are already using the semantically correct `@tag.attribute`. The current Green highlight was chosen because it works well overall with markup languages, so I don't have a strong incentive to amend that just for React.
   If Blue looks better than Green for tag attributes, let's compare a few examples and decide in a separate issue. Also, users are more than welcome to define their own overrides based on personal preferences.

Samples:

tsx

![image](https://user-images.githubusercontent.com/3299086/233977482-e2c9b4de-3b63-4969-a77f-8582b741d252.png)

html (no change)

![image](https://user-images.githubusercontent.com/3299086/233976847-a986a555-9d38-47ed-a2fc-5919b5905750.png)

[^1]: The linked highlights are for Everforest, but Everforest and Gruvbox Material share similar semantics. I'm still working on porting this document to Gruvbox Material.

**Comment by tomasjm** [comment]
Thank you! It looks good now. I will give more feedback if I find issues while working with tsx
