### ISSUE TITLE
Looks bad under transparent background

### ISSUE THREAD

**Issue by wfxr** [sainnhe/gruvbox-material#19]
![image](https://user-images.githubusercontent.com/6105425/69633292-e747e000-108a-11ea-9e3c-840a928e42a6.png)

![image](https://user-images.githubusercontent.com/6105425/69633405-1bbb9c00-108b-11ea-93cc-2e09f32c022c.png)

Original gruvbox theme does not has the problem:
![image](https://user-images.githubusercontent.com/6105425/69633643-97b5e400-108b-11ea-9a66-4b4f0da9becb.png)

**Comment by wfxr** [comment]
Oh I found the solution from #10. After setting the `g:gruvbox_material_transparent_background` the problem has gone :)
Maybe this option should be added in the README.

**Comment by sainnhe** [comment]
Thanks for your suggestion.

Sorry but I don't want to add this to README because I don't encourage users to enable this option, as this color scheme is designed for eye protection and concentration instead of looking cool. To be honest, this color scheme might look better when not in transparent mode.

If you do need transparent, I would recommend you to use composite manager with blur feature, for example [tryone144/compton](https://github.com/tryone144/compton).

Here is a screenshot:

![](https://user-images.githubusercontent.com/37491630/69637420-91c40100-1093-11ea-8728-78244ee2b5f4.png)

**Comment by wfxr** [comment]
Makes sense. I will try it sometime.
