### ISSUE TITLE
Can you share the config files that were used to generate the palette previews using prev_gen by @Aonodensetsu ?

### ISSUE THREAD

**Issue by Vibhav201** [sainnhe/gruvbox-material#191]
I saw in an old PR that [prev_gen](https://github.com/Aonodensetsu/prev_gen/) was used to generate the palette previews for this amazing colour scheme. 

I wanted to have the palette previews in SVG format and it would be a lot easier for me to generate them if you could provide the config files (Python/JSON/TOML/YAML) that were used to generate the palette previews.

If you can please share the prev_gen files of Edge, Sonokai and Everforest as well. If possible please add them to the respective repos as well. SVGs help me to make ports quickly and the config files will help me to customise the palette previews. 

Thanks in advance :)

**Comment by antoineco** [comment]
Tagging @Aonodensetsu

Ref. #164

**Comment by Aonodensetsu** [comment]
that was before i added code re-creation so you'd have to go back to before version 3.0, and use that to recover the colors, i'll look at it

**Comment by Aonodensetsu** [comment]
Get the old palette generator
```bash
pip install prev-gen==2.1
```
Convert to code, color names and settings are manual
```python
from glob import glob
from prev_gen import Reverse
names = [
    ['bg_dim', 'bg0', 'bg1', 'bg2', 'bg3', 'bg4', 'bg5'],
    ['bg_statustline1','bg_statustline2','bg_statustline3','bg_diff_green','bg_visual_green','bg_diff_red','bg_visual_red'],
    ['bg_diff_blue','bg_visual_blue','bg_visual_yellow','bg_current_word','fg0','fg1','red'],
    ['orange','yellow','green','aqua','blue','purple','bg_red'],
    ['bg_green','bg_yellow','grey0','grey1','grey2']
]
for i in glob('*'):
    if '.png' not in i:
        continue
    if 'main' in i:
        continue
    s = f'from prev_gen import Color, Preview, Settings\npalette = [\n  Settings(fileName=\'{i.removesuffix(".png")}\', gridWidth=400, gridHeight=200),'
    t = Reverse(i)
    for r, k in zip(t, names):
        s += '\n  ['
        for c, l in zip(r, k):
            if c:
                s += f'\n    Color(\'{c.hex}\', \'{l}\'),'
        s += '\n  ],'
    s += '\n]\nPreview(palette, save=True, show=False)'
    with open(i.removesuffix('.png') + '.py', 'w') as f:
        f.write(s)
```
Get the new palette generator
```bash
pip install -U prev-gen
```
(Optional) Generate new previews
```python
from glob import glob
for i in glob('*'):
    if '.py' not in i:
        continue
    if 'main' in i:
        continue
    with open(i, 'r') as f:
        exec(f.read())
```
The palettes in new format, which allow `prev_gen --out py filename` to get the code
(and then `prev_gen --unsafe --out svg codefile` for svg previews)
[gruvbox-material.zip](https://github.com/sainnhe/gruvbox-material/files/13851555/gruvbox-material.zip)

Copy the code above (and edit hardcoded values) for other palettes you want, but you can first try to extract code with the command above, because i added the re-creation quite early so hopefully most PNGs out there support it.

While doing this I discovered a bug, so you'll have to go into the generated code and remove the `'None'` strings, since for some reason the unquoting broke.

**Comment by Vibhav201** [comment]
The PNGs I downloaded from Github READMEs don't work directly with this command - `prev_gen --out py filename.png`. So, I guess have to manually edit the script you provided for each palette. Thanks for the help on this.

**Comment by Vibhav201** [comment]
@antoineco I was able to recreate the palette python files with the script that @Aonodensetsu provided so I am closing this issue. If you want to add the files to the respective repos for all of @sainnhe's themes I can share them. Thanks for the help.

**Comment by antoineco** [comment]
Because I just had to regenerate the previews after the changes from f7b152174433c35bbe63e146e9ae9a28c166f47c, let me use the occasion to document my process for future reference.

Like for the previous generations I used [prev_gen](https://github.com/Aonodensetsu/prev_gen) (which has since received quite a few neat improvements!).

I picked the [example.py](https://github.com/Aonodensetsu/prev_gen/blob/e0cb74f00775a15a8e9a607ab7bbe6241ea67f9d/example.py) file from the source repository as a template and filled it using a semi-manual process of copying the `palette1`, `palette2` and `palette3` maps from [gruvbox_material#get_palette](https://github.com/sainnhe/gruvbox-material/blob/cf4709418b4066aee67d9c0bfaa1b0d631ce68a5/autoload/gruvbox_material.vim#L38) then formatting them with the help of a Vim macro.

I did it for all the `else` cases, meaning a combination of `a:foreground = 'original'`, `a:background = 'soft'` and `&background = 'light'`,  in practical terms. You will understand why in a second, but for now here is what I came up with. I made sure that the grid would have all the shades of `red` on the same column, etc. for better visuals:

```python
# original_soft_light.py

palette = [
    {
        "file_name": "original_soft_light",
        "show_hash": True,
        "grid_width": 380,
    },
    [
        ("#ebdbb2", "bg_dim"),
        ("#f2e5bc", "bg0"),
        ("#eddeb5", "bg1"),
        ("#ebdbb2", "bg2"),
        ("#e6d5ae", "bg3"),
        ("#dac9a5", "bg4"),
        ("#d5c4a1", "bg5"),
    ],
    [
        ("#f7d9b9", "bg_diff_red"),
        ("#dfe1b4", "bg_diff_green"),
        ("#dbddbf", "bg_diff_blue"),
        ("#ebdbb2", "bg_statusline1"),
        ("#ebdbb2", "bg_statusline2"),
        ("#dac9a5", "bg_statusline3"),
        ("#ebdbb2", "bg_current_word"),
    ],
    [
        ("#efd2b3", "bg_visual_red"),
        ("#d7d9ae", "bg_visual_green"),
        ("#d3d5b8", "bg_visual_blue"),
        ("#f3deaa", "bg_visual_yellow"),
        ("#e8d4ba", "bg_visual_purple"),
        ("#3c3836", "fg0"),
        ("#3c3836", "fg1"),
    ],
    [
        ("#9d0006", "red"),
        ("#79740e", "green"),
        ("#076678", "blue"),
        ("#b57614", "yellow"),
        ("#8f3f71", "purple"),
        ("#af3a03", "orange"),
        ("#427b58", "aqua"),
    ],
    [
        ("#ae5858", "bg_red"),
        ("#6f8352", "bg_green"),
        ("0000",),
        ("#a96b2c", "bg_yellow"),
        ("#a89984", "grey0"),
        ("#928374", "grey1"),
        ("#7c6f64", "grey2"),
    ],
]

if __name__ == "__main__":
    from prev_gen import Previewer

    Previewer(palette)
```

I then prompted a LLM (Gemini 2.5 Flash did a good job) with the following input:
1. The body of the `gruvbox_material#get_palette` function _(I first tried with the whole file but the context was too large and the LLM produced questionable results)_.
1. Information about how the palette was structured, especially a mention to the `a:background ==# ...`, `a:foreground ==# ...` and `&background ==# ...` conditionals used to determine the values for `palette1`, `palette2` and `palette3` _(a very important input)_.
1. An example of map entry with a mention that the color hex code is the first array element associated with the color name, e.g. `\ bg_red':           ['#ae5858',   '88'],`
1. My `original_soft_light.py` template file above, mentioning that the values in this file were for all the `else` conditions for `a:background`, `a:foreground` and `&background` _(another very important input)_.
1. The instruction to collect the palette colors for the conditional values `&background ==# 'dark'`, `a:background ==# 'hard'`, `a:foreground ==# 'material'`, replace the hex codes in the Python template file with them, and replace the value of the `file_name` attribute following the naming convention `a:foreground_a:background_&background`.
1. After verification, possible re-prompts (e.g. if it picked the wrong conditional block) and final reinforcement to the LLM that it had produced the correct output, I asked it to generate files for _all_ variations:

    > Now that the structure of the file and the conditionals are understood, I want one separate file for each of the following combinations of conditional values:
    > - `&background ==# 'dark'` `a:background ==# 'hard'` `a:foreground ==# 'material'`
    > - `&background ==# 'dark'` `a:background ==# 'medium'` `a:foreground ==# 'material'`
    > - `&background ==# 'dark'` `a:background unspecified (else)` `a:foreground ==# 'material'`
    > - `&background unspecified (else)` `a:background ==# 'hard'` `a:foreground ==# 'material'`
    > - `&background unspecified (else)` `a:background ==# 'medium'` `a:foreground ==# 'material'`
    > - `&background unspecified (else)` `a:background unspecified (else)` `a:foreground ==# 'material'`
    > - `&background ==# 'dark'` `a:background ==# 'hard'` `a:foreground ==# 'mix'`
    > - `&background ==# 'dark'` `a:background ==# 'medium'` `a:foreground ==# 'mix'`
    > - `&background ==# 'dark'` `a:background unspecified (else)` `a:foreground ==# 'mix'`
    > - `&background unspecified (else)` `a:background ==# 'hard'` `a:foreground ==# 'mix'`
    > - `&background unspecified (else)` `a:background ==# 'medium'` `a:foreground ==# 'mix'`
    > - `&background unspecified (else)` `a:background unspecified (else)` `a:foreground ==# 'material'`
    > - `&background ==# 'dark'` `a:background ==# 'hard'` `a:foreground unspecified (else)`
    > - `&background ==# 'dark'` `a:background ==# 'medium'` `a:foreground unspecified (else)`
    > - `&background ==# 'dark'` `a:background unspecified (else)` `a:foreground unspecified (else)`
    > - `&background unspecified (else)` `a:background ==# 'hard'` `a:foreground unspecified (else)`
    > - `&background unspecified (else)` `a:background ==# 'medium'` `a:foreground unspecified (else)`
    > - `&background unspecified (else)` `a:background unspecified (else)` `a:foreground unspecified (else)`

Simply call `prev_gen --unsafe FILENAME.py` on each resulting file to generate the PNG files in the local directory.
