### ISSUE TITLE
Change sitgncolumn bg

### ISSUE THREAD

**Issue by alex-popov-tech** [sainnhe/gruvbox-material#31]
I'm using coc.nvim with gruvbox-material, and when signcolumnt pops out i can see that it has different bg comparing to line number column...how can i fix that?

**Comment by sainnhe** [comment]
It's intentional, I prefer a darker background in `CursorLine`, `CursorColumn` and `CursorLineNr`, because directly use the background color of `SignColumn` will make the `CursorLine` and `CursorColumn` look a little bit wired, especially in light variant.

If you want to use the same background color of `SignColumn`, fork this repo and modify [Line 744 - Line 751](https://github.com/sainnhe/gruvbox-material/blob/285ba13364bea19011cbe6048b96661feba2651b/colors/gruvbox-material.vim#L744-L751) like this:

```vim
:744,751s/bg1/bg2/
```

**Comment by alex-popov-tech** [comment]
@sainnhe thanks for the answer! Could that be done in this repo using an option of some kind? :)

**Comment by sainnhe** [comment]
OK, this might be a better choice because someone else may have the same needs. I'm going to add a new option instead.

**Comment by alex-popov-tech** [comment]
yes, exactly :) thanks, can you please post an update when ready in this thread @sainnhe ? I will subscribe to update my vimrc as soon as that will be filished :)

**Comment by sainnhe** [comment]
Done via 6d4a18b.

**Comment by alex-popov-tech** [comment]
thank you, that is exactly what i needed! closing
