### ISSUE TITLE
Different status-line color on different method.

### ISSUE THREAD

**Issue by rukh-debug** [sainnhe/gruvbox-material#49]
- Operating system/version: Manjaro Linux x86_64
- Terminal emulator/version: kitty 
- `echo $TERM`: xterm-kitty
- `tmux -V`: 
- `vim --version` : VIM - Vi IMproved 8.2

### Actual behaviour
Apparently, when I load airline_theme from .vimrc like this, the statusline is kind of white in color
![image](https://user-images.githubusercontent.com/39809189/96903389-8355b380-14b5-11eb-92f4-96aca5ed42cd.png)

### Expected behaviour
And when I load it from vim neomal mode, it is dark in color for some reason. I want it to be dark in color by default. but cant do the thing from .vimrc
![image](https://user-images.githubusercontent.com/39809189/96903600-c44dc800-14b5-11eb-907a-0b1dec4f3232.png)

**Comment by sainnhe** [comment]
This is not a bug, you didn't set termguicolors, please read [the doc](https://github.com/sainnhe/gruvbox-material/blob/4602d8e4dd73d3f2cbbd6635d4c27d4ebd0a11fb/doc/gruvbox-material.txt#L85-L88).

Or your terminal emulator doesn't support true colors, see [FAQ](https://github.com/sainnhe/gruvbox-material/blob/4602d8e4dd73d3f2cbbd6635d4c27d4ebd0a11fb/doc/gruvbox-material.txt#L456-L457).

I assume that "neomal mode" is neovim, the screenshot is different because &background is 'dark' in neovim by default and is 'light' in vim by default, you need to specify them in your vimrc, see [the doc](https://github.com/sainnhe/gruvbox-material/blob/4602d8e4dd73d3f2cbbd6635d4c27d4ebd0a11fb/doc/gruvbox-material.txt#L90-L94).

Btw, please follow the [issue template](https://github.com/sainnhe/gruvbox-material/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#minimal-vimrc-that-can-reproduce-this-bug) next time, we need minimal vimrc to reproduce the bug.

**Comment by rukh-debug** [comment]
Thanks, that's awesome. I should have read the doc carefully. I am a new vim user so.... sorry to bother.

Btw, thanks for this awesome theme.
