### ISSUE TITLE
comment color

### ISSUE THREAD

**Issue by lemon0910** [sainnhe/gruvbox-material#5]
hi, this my picture, I use mac,  what should I do?
![image](https://user-images.githubusercontent.com/3163925/63020322-634d5c00-bed0-11e9-92bd-222c1d3fba00.png)

**Comment by sainnhe** [comment]
What's the result of this command

```vim
:hi Comment
```

**Comment by lemon0910** [comment]
Comment   xxx term=bold cterm=italic ctermfg=14 gui=italic guifg=#928374

It's ok in neovim, I use vim8.0. I once think it's iterm's problem.

**Comment by sainnhe** [comment]
I can't reproduce this. Please try the following steps:

1. Minimize your vimrc with only this color schemes installed.
2. Enable this color scheme in vimrc instead of after vim startup:

```vim
set termguicolors
colorscheme gruvbox-material
```

If this problem still exists, check output of

```vim
:hi vimLineComment
:hi vimComment
```

In theory, `vimLineComment` should be linked to `vimComment`, and `vimComment` should be linked to `Comment`.

**Comment by lemon0910** [comment]
thanks, I modify comment like this 'hi Comment guifg=#928374 guibg=NONE guisp=NONE gui=italic cterm=NONE', It works for me, thank you. It's a beautiful theme

**Comment by brettinternet** [comment]
I also ran into this. I have to call `hi clear Comment` after `colorscheme gruvbox-material` and I'm not too sure why.

**Comment by glindsell** [comment]
> I can't reproduce this. Please try the following steps:
> 
> 1. Minimize your vimrc with only this color schemes installed.
> 2. Enable this color scheme in vimrc instead of after vim startup:
> 
> ```viml
> set termguicolors
> colorscheme gruvbox-material
> ```
> 
> If this problem still exists, check output of
> 
> ```viml
> :hi vimLineComment
> :hi vimComment
> ```
> 
> In theory, `vimLineComment` should be linked to `vimComment`, and `vimComment` should be linked to `Comment`.

I ran into this issue too with iTerm2. My outputs for the above:

:hi Comment
```
Comment        xxx term=bold cterm=italic ctermfg=245 gui=italic guifg=#928374
```

:hi vimLineComment
```
E411: highlight group not found: vimLineComment
```

:hi vimComment
```
E411: highlight group not found: vimComment
```

Line 4 in my `.vimrc` fixed for me (I think term unable to show italics):
```
syntax on
set termguicolors
colorscheme gruvbox-material
hi Comment term=bold cterm=NONE ctermfg=245 gui=NONE guifg=#928374
```

**Comment by cherrot** [comment]
Thanks for @glindsell  's hint, it is because the `italic` setting.

To fix this, add the following lines before `colorscheme gruvbox-material`:
```vim
let &t_ZH="\e[3m"
let &t_ZR="\e[23m"
" ...
colorscheme gruvbox-material
```

For example in my `.vimrc`:
```vim
if has('termguicolors')
    set termguicolors
endif
if has('gui_running')
    set background=light
else
    set background=dark
endif
let &t_ZH="\e[3m"
let &t_ZR="\e[23m"

" let g:gruvbox_material_disable_italic_comment = 1

colorscheme gruvbox-material
" Be compatible with transparent terminals
" https://stackoverflow.com/questions/37712730/set-vim-background-transparent
hi Normal guibg=NONE ctermbg=NONE
hi EndOfBuffer guibg=NONE ctermbg=NONE
```

Check https://stackoverflow.com/a/21077380/3839186 to test if your terminal supports italic font.

@sainnhe Could we highlight this behaviour in `README.md`, or just set `g:gruvbox_material_disable_italic_comment` default to `0` ?  It's hard to figure out that a comment color issue is caused by a italic font setting 😄

**Comment by sainnhe** [comment]
@cherrot Thank you! I've mentioned your comment in help doc.

**Comment by oswede** [comment]
@cherrot Thanks

**Comment by nabaco** [comment]
In case anyone comes here as I have, there is also an issue with italics in Windows Terminal: https://github.com/microsoft/terminal/issues/14094
