### ISSUE TITLE
lightline/airline colorscheme name is different than colorscheme name

### ISSUE THREAD

**Issue by psych3r** [sainnhe/gruvbox-material#50]
gruvbox material uses gruvbox-material for colorscheme statement 
```
colorscheme gruvbox-material
```
and gruvbox_material for airline/lightline
```
let g:lightline.colorscheme = 'gruvbox_material'
```

This is not ideal because usually we can set
```
let g:airline_theme = g:colors_name
```

So that changing the colorscheme reflects on airline automatically.
This is not the case with gruvbox material.

**Comment by psych3r** [comment]
This can be solved by either changing the file name in colors to gruvbox_material.vim
Or changing the filenames in autoload to gruvbox-material.vim

They really should be matching.

**Comment by sainnhe** [comment]
Well, this is actually because of some historical reasons.

When I created this repository, I named it as `gruvbox-material` instead of `gruvbox_material` because most of repositories use hyphens to separate words, and I decided to use hyphens in the `g:colors_name` because I want to make it coincide with the repository name. At that time I had not yet written an airline theme and everything works fine.

But when I decided to add support for airline/lightline, I realized that I can't use hyphens in the name of airline/lightline theme, because using `-` in a variable name is illegal not only in vim script but in most of programming languages.

However it's too late to change `g:colors_name` to `gruvbox_material`, because many people are already using this color scheme, changing `g:colors_name` means all of them have to modify their vimrc.

So I made a compromise on the naming of airline and lightline theme.

**Comment by psych3r** [comment]
I honestly think you should reconsider, it's a single character change in vimrc. 
I'd argue most if not all people would be glad for it.

**Comment by sainnhe** [comment]
@zxYin What do you think?

**Comment by sainnhe** [comment]
@abdalrahman-ali I have seriously reconsidered, but still decided not to change.

1. Conservative users may not expect their configuration breaks after an update, for example me.

2. As I said above, because the use of hyphens is illegal in naming variables, I can't use `gruvbox-material` in airline/lightline theme, the only solution is changing `g:colors_name` to `gruvbox_material`. However, airline and lightline are just *plugins* of vim, it seems unreasonable to make a compromise on a color scheme because of the plugins, especially for those who don't use airline/lightline and prefer to write their own status lines.

Sorry but as a maintainer, I have to consider many other factors, so I won't change the name. But this is an open source project, you can fork this repository and maintain your own branch, or you can try other alternatives, for example [gruvbox-community/gruvbox](https://github.com/gruvbox-community/gruvbox) is also very nice.

**Comment by crivotz** [comment]
Sorry to jump in on this already closed discussion. But today I didn't understand if with `vim-plug` I had already installed the theme for `lightline` or if I had to do it manually.
Searching through the issues I then found this distinction between the names.
I understand why @sainnhe want to keep it.
You could however underline in the readme so that the difference is immediately obvious.

**Comment by sainnhe** [comment]
@crivotz I have already added it in FAQ.

**Comment by crivotz** [comment]
@sainnhe Thanks my mistake
