### ISSUE TITLE
Treesitter support?

### ISSUE THREAD

**Issue by subnut** [sainnhe/gruvbox-material#63]
Does this colorscheme support treesitter?
If no, then is it planned to support treesitter?

@sainnhe Your other colorschemes `edge` and `sonokai` support treesitter, so why not this one?

Sorry if treesitter support has already been integrated.. I made this issue as soon as I noticed that this colorscheme was absent in [this](https://github.com/nvim-treesitter/nvim-treesitter/wiki/Colorschemes) list

**Comment by sainnhe** [comment]
> Does this colorscheme support treesitter?

Yes, and it's the first to support tree-sitter, much earlier than my other color schemes.

https://github.com/sainnhe/gruvbox-material/commit/16a77e5d890b80fb1e0455edfe205a1da98f3a3e

https://github.com/sainnhe/gruvbox-material/commit/53e749e9fbb717e9648fac732dfb11ec6956c698

https://github.com/nvim-treesitter/nvim-treesitter/issues/120

But looks like tree-sitter has added some new hi groups since June, I plan to support them later.

**Comment by subnut** [comment]
Thanks! 

BTW where do you find all the current hi groups? Is there a list of them or something like that?

**Comment by sainnhe** [comment]
In the [help doc](https://github.com/nvim-treesitter/nvim-treesitter/blob/1ad1f3b35afda469605ea8f6f0961dd4fa58e53d/doc/nvim-treesitter.txt#L397-L599).

**Comment by Mrfiregem** [comment]
Compared to using the polyglot extension, things like arguments/options, and variables aren't highlighted as nicely using treesitter to view bash files.

I'm on a different computer right now so I can't send screenshots or look further atm, but I believe this is the same issue of needing to use new highlighting groups.

**Comment by sainnhe** [comment]
@Mrfiregem I don't think we need to use new hi groups, since all hi groups of tree-sitter have already been added in this color scheme.

If you are not satisfied with this, maybe fork this repository or use custom colors (see FAQ).

**Comment by Mrfiregem** [comment]
Thanks for the quick reply.

Looking again, it seems like the bash plugin just uses very simplistic highlighting groups atm. I'll just disable treesitter highlighting for bash with an aucmd for now and wait for it to mature.

**Comment by ndavd** [comment]
@sainnhe So is this colorscheme up to date with treesitter (i.e. all the 'new' hl_groups added)? If so, maybe this should be added to https://github.com/nvim-treesitter/nvim-treesitter/wiki/Colorschemes so that more people know about it :D

**Comment by sainnhe** [comment]
@ndavidq0 I'm not sure if this should be added to the wiki page, because:

1. Tree-sitter should work out of the box, because all the hi groups are linked to other common hi groups by default. That's said, color schemes like solarized that haven't been updated for a long time should also work with tree-sitter, so I don’t think it makes much sense to add it to the wiki page.
2. So called "all hi groups" are added months ago, I'm not sure if tree-sitter has added any other new hi groups, and since I don't use it, I can't guarantee to keep it up to date in the future, so I don't know if I should add this color scheme to the wiki page.

Btw, my sonokai and edge color scheme in the wiki page were not added by me.

**Comment by ndavd** [comment]
Hm yeah makes sense. Also, if it's not much work, could you update the TS hl_groups from time to time? Even though you don't use it yourself <3

**Comment by sainnhe** [comment]
@ndavidq0 ppl will open an issue if something doesn't work nicely, but I will try my best to keep it up to date.

**Comment by ndavd** [comment]
Thanks @sainnhe this colorscheme is the best (material palette :p)
