### ISSUE TITLE
different color with c++ in vs-code and neovim

### ISSUE THREAD

**Issue by noopenryu** [sainnhe/gruvbox-material#69]
![Screenshot from 2021-01-06 23-36-39](https://user-images.githubusercontent.com/55192418/103795066-1abfb100-5078-11eb-9fa3-ca1df1f8ba29.png)
Help me

**Comment by sainnhe** [comment]
It's intentional, why they should be the same?

The syntax highlighting logic in vim is based on original gruvbox, while the syntax highlighting logic in vscode is designed by myself.

Btw, if you want to try vscode syntax highlighting logic in vim, install the tree-sitter plugin, the syntax highlighting logic used in nvim-treesitter is based on my own design.

And technically, they can't be the same even if they share the same syntax highlighting logic, because these two editor use completely different syntax highlighting technologies.

So, I won't fix this, and also can't fix this. But remember these two projects are OPEN SOURCE, if you're not satisfied with the design of any of them, you can fork the repository and modify the code by yourself.
