### ISSUE TITLE
Hard to read diff parts when using diffchar.vim (hl-SpecialKey)

### ISSUE THREAD

**Issue by Gelio** [sainnhe/gruvbox-material#85]
- Operating system/version: Ubuntu 20.04 LTS
- Terminal emulator/version: Alacritty 0.8.0
- `echo $TERM`: `xterm-256color`
- `tmux -V`: `tmux 3.1b`
- `vim --version` or `nvim --version`: 

```
NVIM v0.5.0-dev+1339-g5d9c56012
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az121-644

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

### Minimal vimrc that can reproduce this bug

```vim
" Install those
Plug 'rickhowe/diffchar.vim'
Plug 'sainnhe/gruvbox-material'


set t_Co=256
colorscheme gruvbox-material
```

### Steps to reproduce this bug using minimal vimrc

1. Insert `a() => ` and `:diffthis`
2. `:vnew` and insert `abce()` and `:diffthis`

### Actual behaviour

Most of the characters are hard to read
![image](https://user-images.githubusercontent.com/889383/118936776-22a82f80-b94d-11eb-8398-69f03d94bd7f.png)

because [diffchar.vim](https://github.com/rickhowe/diffchar.vim) is using `hl-SpecialKey` https://github.com/rickhowe/diffchar.vim/blob/master/autoload/diffchar.vim#L268

### Expected behaviour

`hl-SpecialKey` is more readable so the diffs are easier to read

**Comment by sainnhe** [comment]
I just tried this plugin and found that it only provides 3 custom hi groups:

1. `dcDiffChange`
2. `dcDiffErase`
3. `dcDiffText`

None of them are linked to `SpecialKey`, so I can't fix this by linking hi groups.

It's also not a good idea to change the color of `SpecialKey`, because this hi group is used to display `listchars`, the current color is already very suitable.

So, maybe you can open an issue in diffchar.vim repo and ask the author if it's possible to add a new custom hi group and link it to `SpecialKey`, or you can directly change the color of `SpecialKey` in your vimrc if you don't use `listchars` (see FAQ "How to use custom colors?").

**Comment by Gelio** [comment]
Thank you for putting the time to investigate and leaving the suggestions. I have opened https://github.com/rickhowe/diffchar.vim/issues/27 in that repo
